#!/usr/bin/env python

import requests
import sys

from common import keystone_auth, get_vo_info

if len(sys.argv) != 2:
    print >> sys.stderr, "Missing site URI!"
    sys.exit(1)


base_headers = {'content-type': 'text/occi',
                'accept': 'text/plain,text/occi'}

site_uri = sys.argv[1]
proxy, vo_name = get_vo_info()
r = requests.get(site_uri + "compute/",
                 headers=base_headers,
                 cert=proxy,
                 verify=False)
if r.status_code == 401:
    # Keystone!
    ks_uri = r.headers['www-authenticate'].split('=')[1].strip("\"'")
    kid = keystone_auth(ks_uri, proxy, vo_name)
    base_headers['x-auth-token'] = kid
    r = requests.get(site_uri + "compute/",
                        headers=base_headers,
                        cert=proxy,
                        verify=False)
if r.status_code != 200:
    print "Something went wrong!?"
    print r
    print r.content
    print r.headers
    print r.request.headers
    sys.exit(0)

for l in r.content.split('\n'):
    if l.lower().find('x-occi-location') != -1:
        print l.split(':', 1)[-1].strip()
